background:    "#0F3D51"
border:        "#00819D"
label:         "#F7673B"
text:          "#EFFAFA"
value:         "#44C2DE"
accent:        "#FFA572"
selectionBg:   "#00819D"
selectionText: "#FFFFFF"
statusBarBg:   "#F7673B"
statusBarText: "#0F3D51"
views:
  home:     "#44C2DE"
  settings: "#FFA572"
  queues:   "#00819D"
  log:      "#B8EAF1"
