openapi: 3.1.0
info:
  title: mq-proxy API
  description: ActiveMQ broker proxy
  version: "1.0"
servers:
- url: http://localhost:8080
  description: Generated server url
security:
- basicAuth: []
paths:
  /api/management/command/send-message:
    post:
      tags:
      - queue-controller
      operationId: sendMessage
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SendMessageRequest"
        required: true
      responses:
        "500":
          description: Internal Server Error
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ItemResponseSendMessageResponseDto"
  /api/management/command/move-messages:
    post:
      tags:
      - queue-controller
      operationId: moveMessages
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/MoveMessagesRequest"
        required: true
      responses:
        "500":
          description: Internal Server Error
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ListResponseMovedMessageDto"
  /api/management/command/delete-messages:
    post:
      tags:
      - queue-controller
      operationId: deleteMessages
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/DeleteMessagesRequest"
        required: true
      responses:
        "500":
          description: Internal Server Error
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ListResponseDeletedMessageDto"
  /api/management/command/list-queues:
    get:
      tags:
      - queue-controller
      operationId: listQueues
      responses:
        "500":
          description: Internal Server Error
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ListResponseQueueSummary"
  /api/management/command/list-messages:
    get:
      tags:
      - queue-controller
      operationId: listMessages
      parameters:
      - name: query
        in: query
        required: true
        schema:
          $ref: "#/components/schemas/ListMessagesQuery"
      responses:
        "500":
          description: Internal Server Error
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: string
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ListResponseMessageSummary"
components:
  schemas:
    SendMessageRequest:
      type: object
      properties:
        targetQueue:
          type: string
        jmsType:
          type: string
        headers:
          type: object
          additionalProperties:
            type: string
        groupId:
          type: string
        body:
          type: string
        correlationId:
          type: string
      required:
      - body
      - jmsType
      - targetQueue
    ApiError:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
      - code
      - message
    ItemResponseSendMessageResponseDto:
      type: object
      properties:
        data:
          $ref: "#/components/schemas/SendMessageResponseDto"
        error:
          $ref: "#/components/schemas/ApiError"
    SendMessageResponseDto:
      type: object
      properties:
        messageId:
          type: string
      required:
      - messageId
    MoveMessagesRequest:
      type: object
      properties:
        sourceQueue:
          type: string
        targetQueue:
          type: string
        filter:
          $ref: "#/components/schemas/QueueMessageFilter"
      required:
      - filter
      - sourceQueue
      - targetQueue
    QueueMessageFilter:
      type: object
      properties:
        jmsType:
          type: string
        fromDate:
          type: string
        toDate:
          type: string
        messageId:
          type: string
        maxCount:
          type: integer
          format: int32
    ListResponseMovedMessageDto:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: "#/components/schemas/MovedMessageDto"
        errors:
          type: array
          items:
            $ref: "#/components/schemas/ApiError"
      required:
      - data
      - errors
    MovedMessageDto:
      type: object
      properties:
        messageId:
          type: string
      required:
      - messageId
    DeleteMessagesRequest:
      type: object
      properties:
        sourceQueue:
          type: string
        filter:
          $ref: "#/components/schemas/QueueMessageFilter"
      required:
      - filter
      - sourceQueue
    DeletedMessageDto:
      type: object
      properties:
        messageId:
          type: string
      required:
      - messageId
    ListResponseDeletedMessageDto:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: "#/components/schemas/DeletedMessageDto"
        errors:
          type: array
          items:
            $ref: "#/components/schemas/ApiError"
      required:
      - data
      - errors
    ListResponseQueueSummary:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: "#/components/schemas/QueueSummary"
        errors:
          type: array
          items:
            $ref: "#/components/schemas/ApiError"
      required:
      - data
      - errors
    QueueSummary:
      type: object
      properties:
        name:
          type: string
        messageCount:
          type: integer
          format: int64
        consumerCount:
          type: integer
          format: int64
        enqueuedCount:
          type: integer
          format: int64
        dequeuedCount:
          type: integer
          format: int64
        producerCount:
          type: integer
          format: int64
      required:
      - consumerCount
      - dequeuedCount
      - enqueuedCount
      - messageCount
      - name
      - producerCount
    ListMessagesQuery:
      type: object
      properties:
        sourceQueue:
          type: string
        returnBody:
          type: boolean
        filter:
          $ref: "#/components/schemas/QueueMessageFilter"
      required:
      - filter
      - sourceQueue
    ListResponseMessageSummary:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: "#/components/schemas/MessageSummary"
        errors:
          type: array
          items:
            $ref: "#/components/schemas/ApiError"
      required:
      - data
      - errors
    MessageSummary:
      type: object
      properties:
        sourceQueue:
          type: string
        messageId:
          type: string
        jmsType:
          type: string
        body:
          type: string
        timestamp:
          type: string
        headers:
          type: object
          additionalProperties:
            type: string
      required:
      - jmsType
      - messageId
      - sourceQueue
      - timestamp
  securitySchemes:
    basicAuth:
      type: http
      description: Proxy credentials (proxy.auth.username / proxy.auth.password)
      scheme: basic
